[package]
name = "unshell-obfuscate"
edition = "2024"

[lib]
proc-macro = true

[features]
# default = ["obfuscate"]
obfuscate = []

[dependencies]
quote = "1.0.42"
syn = {version = "2.0.109", features = ["full"]}
proc-macro2 = "1.0.103"

unshell-crypt = {path = "../unshell-crypt"}
