[package]
name = "unshell-crypt"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8.4"
block-padding = "0.4.1"
cbc = "0.1.2"
getrandom = "0.3.4"
hex = "0.4.3"
hex-literal = "1.1.0"
regex = "1.12.2"
sha2 = "0.10.9"
