[package]
name = "unshell-module-load"
version = "0.1.0"
edition = "2024"

[dependencies]
libloading = "0.8.9"
log = "0.4.28"
pretty_env_logger = "0.5.0"
unshell-logger = {path = "../unshell-logger"}
unshell-modules = {path = "../unshell-modules"}
