[package]
name = "unshell-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
libloading = {version = "0.8.9"}
bincode = "2.0.1"
unshell-obfuscate = {path = "../unshell-obfuscate"}
chrono = "0.4.42"
